### ISSUE TITLE
Review LOINC 4546-8, 4552-6

### ISSUE THREAD

**Issue by kingmanzhang** [TheJacksonLaboratory/loinc2hpoAnnotation#111]
@callahantiff

**Comment by nicolevasilevsky** [comment]
This one looks okay to me

**Comment by callahantiff** [comment]
Agreed, the annotations to 4546-8 and 4552-6, specifically:
-**Normal:**  NOT(HP:0011902)
- **Low:** HP:0011905
- **High:** HP:0011902

look good. We could consider adding a new term for the high Hemoglobin A2 (4552-6) result since that appears to also be abnormal (https://en.wikipedia.org/wiki/Hemoglobin_A2).

I'm not sure what a more specific term for 4546-8 would be.

**Comment by kingmanzhang** [comment]
ok, I have removed the flags from them.
