### ISSUE TITLE
Proposed new annotation format

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/loinc2hpoAnnotation#137]
Please see README and [loinc2hpo-annotations.tsv](https://github.com/TheJacksonLaboratory/loinc2hpoAnnotation/blob/master/loinc2hpo-annotations.tsv). I think this format is a little easier to understand. Also, POS and NEG are typically misunderstood and I think it would be clearer to replace them with PRESENT and ABSENT.
Thoughts?
@iimpulse

**Comment by kingmanzhang** [comment]
The new table looks awesome!

POS and NEG were chosen because they were standard concepts in FHIR (along with L, H, N, A). Back then we thought relying on some existing vocabulary rather than inventing new ones will help adoption.

https://www.hl7.org/fhir/v3/ObservationInterpretation/cs.html

If you look at the FHIR vocabulary, it also has similar concepts to PRESENCE/ABSENCE, ND and DET, but they have more strict definition, i.e. below detection limit is NEGATIVE, but is not necessarily equal to ABSENCE. See below.


Level | Code | Display | Definition
-- | -- | -- | --
2 | NEG | Negative | An absence finding of the specified component / analyte, organism or clinical sign based on the established threshold of the performed test or procedure.[Note: Negative does not necessarily imply the complete absence of the specified item.]
2 | POS | Positive | A presence finding of the specified component / analyte, organism or clinical sign based on the established threshold of the performed test or procedure.
3 | ND | Not detected | The presence of the specified component / analyte, organism or clinical sign could not be determined within the limit of detection of the performed test or procedure.
3 | DET | Detected | The measurement of the specified component / analyte, organism or clinical sign above the limit of detection of the performed test or procedure.

I do not really get what you meant by saying "POS and NEG are typically misunderstood". I probably would prefer to stick to NEG and POS.

**Comment by kingmanzhang** [comment]
Looking at the above table, ND/DET could replace NEG/POS?

**Comment by pnrobinson** [comment]
I think NEG and POS are more general terms. I will finalize the conversion to the new format. The loinc2hpo library now expects that new format as well and runs through without errors.
