### ISSUE TITLE
question about LOINC code CD4+CD25+ cells in blood

### ISSUE THREAD

**Issue by nicolevasilevsky** [TheJacksonLaboratory/loinc2hpoAnnotation#36]
There are a couple codes:
CD4+CD25+ cells/100 in blood
CD4+CD25+ cells [#volume] in blood

There is the class HP_0030335 'Abnormal CD4-positive, CD25-positive, alpha-beta regulatory T cell count'

but I remember colleagues in graduate school saying that you couldn't call a CD4+CD25+ cell a Treg unless you had also demonstrated it was functionality as well, ie, these markers are not enough.

Should I request a NTR for abnormal CD4+CD25+ T cell count (and that can be a parent class)?

**Comment by pnrobinson** [comment]
@nicolevasilevsky I think this is what you were talking about 

Taken together, both the in vivo and in vitro studies strongly support the view that the CD4+CD25+ population represents a unique lineage of regulatory T cells. However, CD25, the most suitable marker for identification of this population, is also expressed by all recently activated T cells. Although the mere acquisition of CD25 expression does not induce the suppressor phenotype , it is difficult to rule out the possibility that this population of T cells, constitutively expressing CD25, also contains a certain percentage of normal activated or memory T cells.  (See https://www.cell.com/fulltext/S1074-7613(02)00280-7)

Here https://www.ncbi.nlm.nih.gov/labs/pmc/articles/PMC2784904/ we read that CD25 is commonly used as a marker but that Unfortunately, accumulating evidence suggests that the above-listed markers are not strictly Treg-specific. 

This has been a recurrent issue with the cell markers for immunology, and we did not find a 100% suitable solution. I think that the immunologists basically told us that they prefer a functional classification of cells over the strict marker-based classification, which is not always reliable. For now, I would suggest let us live with this simplification because it will at least usually be correct. At some point we need to revist the entire marker hierarchy in HPO

**Comment by pnrobinson** [comment]
added
