### ISSUE TITLE
pH in urine by test strip

### ISSUE THREAD

**Issue by jpgourdine** [TheJacksonLaboratory/loinc2hpoAnnotation#4]
Hi Aaron @kingmanzhang I am not sure for the term "pH in urine by test strip" (5803-2) if it is equivalent to impaired urinary acidification. I was not able to flag it or to suggest a term anymore. I annotated with impaired urinary acidification. 
Also, there is another "pH in the urine by automated test strip" (50560-2). Are they the same or different ones ?
Thanks

**Comment by kingmanzhang** [comment]
Hi JP, what do you mean that you were "not able to flag it or to suggest a term"? Why not?

**Comment by jpgourdine** [comment]
I think I mistook pH in urine by test strip" (5803-2) and "pH in the urine by automated test strip" (50560-2). One is already (5803-2) and the other is not. I will edit a comment on that.

**Comment by kingmanzhang** [comment]
@jpgourdine There are potentially many similar LOINC tests for similar things. What you observed above is pretty frequent. "pH in urine by test strip" (5803-2) and "pH in the urine by automated test strip" (50560-2) are DIFFERENT lab tests (have different LOINC codes); at the same time, they are testing on the same thing (pH in urine). Generally, those LOINC codes will be annotated to same HPO terms. 

An extreme of this situation can be demonstrated with glucose chanllenge tests, in which a patient is fed with 100g glucose and then urine glucose is measured at 0.5hr, 1hr, 2hr, 3hr, 4hr, 5hr, 6hr. Each measurement is actually taken as a separated LOINC code. This is decided by the LOINC people and the purpose is to modularize information transmission. How do we annotate those LOINC codes? I think we should annotate them to same HPO terms, which is to say if the patient has high urine glucose at 0.5hr or 1hr or 2hr etc, he has hyperglycemia. This might not make sense in our application because we may decide that three values has to be higher than normal to call it "hyperglycemia". But we will delay this judgement to the application of the annotations. @pnrobinson @nicolevasilevsky @LCCarmody  We may need to discuss this.

**Comment by kingmanzhang** [comment]
I reopen this ticket for other people's input.

**Comment by pnrobinson** [comment]
fixed the error.
